---
name: Update Alpine Dockerfile

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      updatedockerfile: ${{ steps.filter.outputs.updatedockerfile }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Find changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            updatedockerfile:
              - 'Dockerfile'

  build:
    name: Update Dockerfile
    runs-on: ubuntu-latest
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.updatedockerfile == 'true' }}
    permissions:
      pull-requests: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: apt-get install -fy xmllint curl

      - name: Perform Update
        run: ./alpine_package_finder.bash -i apk.txt -o apk-lock.txt -b "$(sed -Ene 's/[[:space:]]*from[[:space:]]*alpine:([[:digit:]]*.[[:digit:]]*).*/v\1/Ip' < Dockerfile)"

      - name: Create commit with changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "[Pin Package Files]"
